### ISSUE TITLE
Is the backbone LLM 7B or 13B LLaMA?

### ISSUE THREAD

**Issue by rperi** [0nutation/SpeechGPT#10]
The [paper](https://arxiv.org/pdf/2305.11000.pdf) mentions the use of 13B LLaMA backend, however the repository uses 7B model. Which is the correct one? Am I missing something?

**Comment by 0nutation** [comment]
In our paper, we used LLaMA 13B, but due to resource constraints and for easier deployment, we retrained on the 7B LLaMA model and open source this 7B version. If we have sufficient computing resources in the future, we will retrain a better 13B version and release it as open source.

**Comment by rperi** [comment]
Thanks for the clarification!

**Comment by mixiazhiyang** [comment]
can you be more specific about the LLAMA version of your released lora weights? Should I add lora to LLAMA or model trained in previous stage? It can be difficult to load correct weights with lora. Is it meta-llama/Llama-2-7b or meta-llama/Llama-2-7b-hf or meta-llama/Llama-2-7b-chat or something else? There is no declaration in the code. Thank you!
