### ISSUE TITLE
ModuleNotFoundError: No module named 'speechgpt'

### ISSUE THREAD

**Issue by DinukaGunaratne** [0nutation/SpeechGPT#28]
s2u_dir="speechgpt/utils/speech2unit/"; vocoder_dir="speechgpt/utils/vocoder/"; python3 speechgpt/src/infer/cli_infer.py --model-name-or-path "SpeechGPT-7B-cm" --lora-weights "SpeechGPT-7B-com" --s2u-dir "${s2u_dir}" --vocoder-dir "${vocoder_dir}" --output-dir "output/" 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/jinda/anaconda3/envs/SpeechGPT/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/jinda/anaconda3/envs/SpeechGPT/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/jinda/anaconda3/envs/SpeechGPT did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/jinda/anaconda3/envs/SpeechGPT/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/polaris'), PosixPath('@/tmp/.ICE-unix/590516,unix/polaris')}
  warn(msg)
/home/jinda/anaconda3/envs/SpeechGPT/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/bin/im-launch /usr/bin/env LD_LIBRARY_PATH= xfce4-session')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Loading binary /home/jinda/anaconda3/envs/SpeechGPT/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda122.so...
2024-04-23 00:19:50 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "speechgpt/src/infer/cli_infer.py", line 14, in <module>
    from speechgpt.utils.speech2unit.speech2unit import Speech2Unit
ModuleNotFoundError: No module named 'speechgpt'

**Comment by Liujingxiu23** [comment]
@rrscholarship  same problem， do you know how to fix it?

**Comment by VJJJJJJ1** [comment]
same error，how do you fix this error？
