### ISSUE TITLE
text2unit.pt not released?

### ISSUE THREAD

**Issue by NoFish-528** [0nutation/SpeechGPT#7]
Thanks for your release code and ckpt, but when I download text2unit.pt it always ERROR. Then I checked the huggingface fnlp and I didn't fine the text2unit repo and relevant ckpt

**Comment by 0nutation** [comment]
Thanks for your attention! I'm so sorry that I forgot to make that repository public. It's now accessible.

**Comment by NoFish-528** [comment]
> Thanks for your attention! I'm so sorry that I forgot to make that repository public. It's now accessible.

thx！that's a promising work!
