### ISSUE TITLE
Are the 2 released datasets identical?

### ISSUE THREAD

**Issue by SchweitzerGAO** [0nutation/SpeechGPT#9]
Thank you for you open-source! I have been anticipating for this so long! I just wonder if the 2 released datasets are identical as the link redirected me to the same page.
P.S. here is a typo😜
![image](https://github.com/0nutation/SpeechGPT/assets/64410968/76849037-14e5-4ddc-ab6a-7f3c39cc3c1b)

**Comment by 0nutation** [comment]
Thank you for your interest! You can find the two released datasets in the two JSONL files within the linked repository. Thanks again for pointing out the typo!

**Comment by SchweitzerGAO** [comment]
Thanks!
